# Generated by Django 6.0.6 on 2026-06-22 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pdfdocument',
            name='uploaded_by',
        ),
    ]
