# Generated by Django 6.0.6 on 2026-06-24 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_api', '0003_qarecord'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QARecord',
        ),
    ]
